version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    command: ["sh", "./entrypoint.sh"]
    volumes:
      - ./:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media  
    env_file:
      - .env
    depends_on:
      - postgres_db
    networks:
      - my_network

  

  postgres_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - my_network

  
volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
